package.json, src/app.js, src/components/footer/index.js, src/components/header/index.js, src/components/item-categories/index.js, src/components/item-comment/index.js, src/components/item-comments/index.js, src/components/item-info/index.js, src/components/item-rating-lite/index.js, src/components/item-rating/index.js, src/components/pagination/index.js, src/components/related-purchase-item/index.js, src/components/related-purchase-items/index.js, src/components/search-box/index.js, src/components/search-result-item/index.js, src/components/search-results-description/index.js, src/components/search-results/index.js, src/hoc/layout.js, src/hoc/routes.js, src/pages/book-detail/__test__/book-detail.spec.js, src/pages/book-detail/index.js, src/pages/home/__test__/home.spec.js, src/pages/home/index.js, yarn.lock
feat: preparation of initial app structure
=> feat: preparation of initial app structure

src/app.js, src/components/layout/index.js, src/routes.js
fix: realocation of layout and routes files
=> fix: realocation of layout and routes files

.circleci/config.yml
- Fixed ci configuration to no deploy functions
=> fix: fixed ci configuration to no deploy functions

functions/libs/algolia/index.js, functions/src/firestore/createBookInAlgolia/index.js, functions/src/firestore/updateBookInAlgolia/index.js
- Fixed cloud functions to no saving unnecessary attributes in algolia
=> fix: cloud functions

functions/src/firestore/createBookInAlgolia/index.js, functions/src/firestore/updateBookInAlgolia/index.js, functions/src/helpers/getRatingCount.js
- Added added rating count att to algolia func sync
=> feat: added rating count att to algolia

package.json, yarn.lock
-  Fixed styled rainbow-theme conflict
=> fix: fixed styled rainbow-theme conflict

src/components/header/styled.js, src/components/layout/styled.js, src/pages/home/index.js, src/pages/home/styled.js, src/styled.js
=> feat: add home animation

src/components/helpers/index.js, src/components/item-categories/styled.js, src/components/item-info/index.js, src/components/item-info/styled.js, src/components/item-rating/styled.js, src/components/layout/styled.js, src/components/search-results-totals/styled.js, src/pages/home/styled.js, src/styled.js
=> feat: add home theme

src/components/footer/styled.js, src/components/item-info/index.js, src/components/item-info/styled.js, src/components/item-related-purchase/styled.js, src/components/item-review-comment/styled.js, src/components/item-review-stats/styled.js, src/components/item-stats/index.js, src/components/subtitle/styled.js, src/pages/book/index.js
=> feat: detail page theming

src/components/header/index.js
fix: add homePage link to heading logo
=> fix: add homePage link to heading logo

src/components/header/index.js, src/components/icons/git/index.js
fix: change git icon color on switch theme
=> fix: change git icon color on switch theme

src/components/item-review-stats/index.js, src/helpers/getRatingCount.js, src/helpers/getStatsFromStars.js, src/pages/book/index.js, src/pages/book/styled.js
=> feat: added book detail data

src/components/item-categories/styled.js, src/components/search-result-item/index.js, src/components/search-result-item/styled.js
fix: results rows rating wrapper
-
=> fix: search results; rating was collapsing on certain widths

src/components/header/styled.js, src/components/search-result-item/index.js, src/components/search-result-item/styled.js, src/components/search-results-totals/index.js, src/pages/home/index.js, src/pages/home/styled.js
-Fixed margin layout. Fix link to detail page. Fix warning when renderIf component is used. Fix animation details in home page.
=> fix: fixed margin, animation and rooting details

src/components/icons/index.js, src/components/icons/no-result-icon/index.js, src/components/no-find-result/index.js, src/components/no-find-result/styled.js, src/pages/home/index.js, src/pages/home/styled.js
fix: #40 #43 
- Added no result message. Fix title margin. 
=> feat: added no result component

src/components/back-link/styled.js, src/components/layout/index.js, src/pages/book/index.js
fix: back link width(position) update
=> fix: back link width(position) update

src/components/item-rating/index.js, src/components/item-rating/styled.js, src/components/search-result-item/index.js, src/components/search-result-item/styled.js, src/components/search-results-totals/index.js, src/components/search-results-totals/styled.js, src/pages/book/styled.js
fix: ui on mobile
--
* search results label - added spacing (next to pagination) on mobile
* center rating and categories on search results
* reverse label inside rating component on mobile
=> fix: ui on mobile

src/algoliaClient.js, src/components/item-related-purchase/index.js, src/components/search-result-item/styled.js, src/pages/book/index.js, src/pages/home/index.js, src/services/algolia/index.js
fix: #36 
- Loaded related books in detail page
=> feat: added related books to detail page

src/helpers/getNRandomFromArray.js, src/helpers/getRatingCount.js, src/helpers/getStatsFromStars.js, src/pages/book/index.js, src/services/algolia/index.js
fix: #
- Fixed related books to no repeat showed book
=> fix: fixed related books to no repeat showed book

src/components/back-link/styled.js, src/components/header/styled.js, src/components/item-info/styled.js, src/components/item-rating/styled.js, src/components/item-related-purchase/styled.js, src/components/item-related-purchases/styled.js, src/components/item-review-comment/styled.js, src/components/item-review-comments/styled.js, src/components/item-review-stats/styled.js, src/components/pagination/styled.js, src/components/recent-item/styled.js, src/components/search-result-item/styled.js, src/components/search-results-description/styled.js, src/constants.js, src/pages/book/styled.js, src/pages/home/styled.js
fix: update breaking points usage
* added constant file to export breaking points
* breaking points added to styled element if needed (replacement of manual breaking points)
=> fix: update breaking points usage

src/algolia-components/search-input/index.js, src/app.js, src/components/item-info/index.js, src/components/item-info/styled.js, src/components/item-related-purchase/index.js, src/components/item-related-purchase/styled.js, src/components/item-review-comment/styled.js, src/components/item-review-stats/index.js, src/components/item-stats/index.js, src/components/item-stats/styled.js, src/components/layout/styled.js, src/components/subtitle/styled.js, src/pages/book/dummyData.js, src/pages/book/index.js, src/pages/home/index.js
-Fixed colors and related books details
=> fix: fix color and related book details

src/components/item-related-purchase/styled.js
feat: add gradient overlay color to related items
=> feat: add gradient overlay color to related items
